In [19]:
from sklearn import datasets
import pandas as pd
from sklearn import preprocessing
boston = datasets.load_boston()
x = pd.DataFrame(preprocessing.scale(boston.data), columns=boston.feature_names)
y = pd.DataFrame(boston.target)

In [21]:
from sklearn import cross_validation
fold = cross_validation.KFold(len(x), n_folds=5, shuffle=True, random_state=42)

In [ ]:
import numpy
from sklearn import neighbors
best_p, max_score = 0., 0.
for p in numpy.linspace(1, 10, 200):
    knn_regressor = neighbors.KNeighborsRegressor(n_neighbors=5, weights='distance', metric='minkowski', p=p)
    res = cross_validation.cross_val_score(knn_regressor, x, y=y, cv=fold, scoring='mean_squared_error')
    print(res)
    score = sum(res) / len(res)
    if score > max_score:
        max_score = score
        best_p = p
(best_p, max_score)

[-20.30046627 -12.49654829 -17.22472776 -11.87854245 -18.35075777]
[-20.30936136 -12.57518095 -17.43989023 -11.99656981 -19.69940066]
[-20.21826497 -12.65570385 -17.6910385  -11.84438336 -19.42675543]
[-20.29172246 -12.96236944 -17.66172812 -11.83692363 -19.45995029]
[-19.94455362 -12.90239665 -18.02413652 -11.87607612 -19.5292402 ]
[-19.81574375 -12.87552199 -17.94073296 -12.03563102 -19.86518631]
[-19.93629151 -13.2445186  -17.98047082 -12.01903767 -19.90344308]
[-19.85260534 -13.80792894 -17.68744093 -12.5911069  -20.07047786]
[-19.83923568 -13.93945557 -17.88983472 -12.60172697 -19.94953394]
[-19.8227108  -13.98580733 -19.20086415 -12.58117569 -19.88249519]
[-19.86942918 -13.6955442  -19.07444959 -12.89780453 -20.06284804]
[-19.8030091  -13.77622656 -19.02286461 -12.93224844 -19.22240171]
[-19.95623454 -13.85147188 -19.12822898 -13.31283514 -19.19586284]
[-19.67860015 -13.94869143 -19.30429356 -13.3834018  -17.6404152 ]
[-19.67314863 -13.91765378 -19.7022669  -13.91751714 -17.64383